version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Phuc2005@
      MYSQL_DATABASE: blogmana
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: src/main/java/backend
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blogmana
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Phuc2005@
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: src/main/java/frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
